### ISSUE TITLE
"Quit" shortcut does not work while image is opened

### ISSUE THREAD

**Issue by Betaversiondot** [oferkv/phototonic#171] opened 2015-01-12 11:06 UTC
When viewing image, to close Phototonic i have to press "Esc", then "Ctrl+Q". It would be better to simply press "Ctrl+Q".

**Comment by oferkv** [comment] 2015-01-12 19:01
Hey Betaversiondot, thanks for the bug, are you sure this reproduces?
I tried reproducing it but could not, are you using the git version or the release version?
Also, if this reproduces, can you please post your config here? (~/.config/phototonic/phototonic_103.conf).

**Comment by Betaversiondot** [comment] 2015-01-12 19:39
Yes, its reproducible. Im using 1.4-2 version (thats the only available in Debian's repository).

[General]
Geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x1\0\0\0\0\x1\xfc\0\0\x1\x11\0\0\x5\x1d\0\0\x3\x82\0\0\x1\xfd\0\0\x1'\0\0\x5\x1c\0\0\x3~\0\0\0\0\0\0)
LockDocks=true
WindowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\x2\0\0\0\0\0\0\x1\0\0\0\x2\b\xfc\x2\0\0\0\x2\xfb\0\0\0\x16\0\x46\0i\0l\0\x65\0 \0S\0y\0s\0t\0\x65\0m\x1\0\0\0:\0\0\x1\x14\0\0\0\x45\0\a\xff\xff\xfb\0\0\0\x14\0I\0m\0\x61\0g\0\x65\0 \0I\0n\0\x66\0o\x1\0\0\x1T\0\0\0\xee\0\0\0\x45\0\a\xff\xff\0\0\0\x1\0\0\0\xb4\0\0\x2\b\xfc\x2\0\0\0\x1\xfb\0\0\0\f\0V\0i\0\x65\0w\0\x65\0r\x1\0\0\0:\0\0\x2\b\0\0\0\x43\0\a\xff\xff\0\0\x1`\0\0\x2\b\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x1\0\0\0\x2\0\0\0\x3\0\0\0\b\0\x45\0\x64\0i\0t\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x14\0N\0\x61\0v\0i\0g\0\x61\0t\0i\0o\0n\x1\0\0\0\xb5\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\b\0V\0i\0\x65\0w\x1\0\0\x2T\xff\xff\xff\xff\0\0\0\0\0\0\0\0)
backgroundColor=@Variant(\0\0\0\x43\x1\xff\xff\x19\x19\x19\x19\x19\x19\0\0)
backgroundThumbColor=@Variant(\0\0\0\x43\x1\xff\xff\xc8\xc8\xc8\xc8\xc8\xc8\0\0)
defaultSaveQuality=100
editToolBarVisible=true
enableAnimations=true
enableImageInfoFS=false
exifRotationEnabled=true
exifThumbRotationEnabled=false
exitInsteadOfClose=0
fsDockVisible=true
goToolBarVisible=true
iiDockVisible=true
imageZoomFactor=@Variant(\0\0\0\x87?\x80\0\0)
isFullScreen=true
lastDir=
noEnlargeSmallThumb=true
pvDockVisible=true
reverseMouseBehavior=false
shouldMaximize=false
showHiddenFiles=false
showLabels=true
slideShowDelay=5
slideShowRandom=false
smallIcons=false
specifiedStartDir=
startupDir=0
textThumbColor=@Variant(\0\0\0\x43\x1\xff\xff\x19\x19\x19\x19\x19\x19\0\0)
thumbLayout=0
thumbPagesReadahead=2
thumbSpacing=3
thumbsSortFlags=16
thumbsZoomVal=150
viewToolBarVisible=true
wrapImageList=false
zoomInFlags=3
zoomOutFlags=1

[Shortcuts]
%U0412%U0432%U0435%U0440%U0445=Alt+Up
%U0412%U043D%U0438%U0437=Ctrl+End
%U0412%U043E%20%U0432%U0435%U0441%U044C%20%U044D%U043A%U0440%U0430%U043D=F
%U0412%U043F%U0435%U0440%U0451%U0434=Alt+Right
%U0412%U0441%U0442%U0430%U0432%U0438%U0442%U044C%20%U0437%U0434%U0435%U0441%U044C=Ctrl+V
%U0412%U0441%U0442%U0430%U0432%U0438%U0442%U044C%20%U0438%U0437%U043E%U0431%U0440%U0430%U0436%U0435%U043D%U0438%U0435=Ctrl+Shift+V
%U0412%U044B%U0439%U0442%U0438=Ctrl+Q
%U0412%U044B%U0440%U0435%U0437%U0430%U0442%U044C=Ctrl+X
%U0414%U0432%U0430%U0436%U0434%U044B=Ctrl+2
%U0414%U0432%U0430%U0436%U0434%U044B%20%U043F%U043E%20%U0432%U0435%U0440%U0442%U0438%U043A%U0430%U043B%U0438=Ctrl+4
%U0417%U0430%U043A%U0440%U044B%U0442%U044C%20%U0438%U0437%U043E%U0431%U0440%U0430%U0436%U0435%U043D%U0438%U0435=Esc
%U0417%U0430%U043F%U0440%U0435%U0442%U0438%U0442%U044C=Ctrl+1
%U0418%U0441%U0445%U043E%U0434%U043D%U044B%U0439%20%U0440%U0430%U0437%U043C%U0435%U0440=Alt+Z
%U041A%U043E%U043F%U0438%U0440%U043E%U0432%U0430%U0442%U044C=Ctrl+C
%U041A%U043E%U043F%U0438%U0440%U043E%U0432%U0430%U0442%U044C%20%U0438%U0437%U043E%U0431%U0440%U0430%U0436%U0435%U043D%U0438%U0435=Ctrl+Shift+C
%U041A%U043E%U043F%U0438%U0440%U043E%U0432%U0430%U0442%U044C%20%U0438%U043B%U0438%20%U043F%U0435%U0440%U0435%U043C%U0435%U0441%U0442%U0438%U0442%U044C%20%U0432...=M
%U041C%U0430%U0441%U0448%U0442%U0430%U0431%U0438%U0440%U043E%U0432%U0430%U0442%U044C%20%U0438%U0437%U043E%U0431%U0440%U0430%U0436%U0435%U043D%U0438%U0435=Ctrl+L
%U041D%U0430%U0437%U0430%U0434=Alt+Left
%U041D%U0430%U0441%U0442%U0440%U043E%U0439%U043A%U0438=P
%U041E%U0431%U043D%U043E%U0432%U0438%U0442%U044C=F5
%U041E%U0431%U0440%U0435%U0437%U043A%U0430=Ctrl+R
%U041E%U0441%U0442%U0430%U0432%U043B%U044F%U0442%U044C%20%U043F%U0440%U0435%U043E%U0431%U0440%U0430%U0437%U043E%U0432%U0430%U043D%U0438%U044F=
%U041E%U0442%U0434%U0430%U043B%U0438%U0442%U044C=Shift+Z
%U041E%U0442%U043A%U0440%U044B%U0442%U044C=Return
%U041E%U0442%U0440%U0430%U0437%U0438%U0442%U044C%20%U043F%U043E%20%U0432%U0435%U0440%U0442%U0438%U043A%U0430%U043B%U0438=Ctrl+Up
%U041E%U0442%U0440%U0430%U0437%U0438%U0442%U044C%20%U043F%U043E%20%U0433%U043E%U0440%U0438%U0437%U043E%U043D%U0442%U0430%U043B%U0438=Ctrl+Down
%U041F%U0435%U0440%U0432%U043E%U0435=Home
%U041F%U0435%U0440%U0435%U0438%U043C%U0435%U043D%U043E%U0432%U0430%U0442%U044C=F2
%U041F%U043E%U0432%U0435%U0440%U043D%U0443%U0442%U044C%20%U043D%U0430%201%B0%20%U043F%U043E%20%U0447%U0430%U0441%U043E%U0432%U043E%U0439%20%U0441%U0442%U0440%U0435%U043B%U043A%U0435=Ctrl+Shift+Right
%U041F%U043E%U0432%U0435%U0440%U043D%U0443%U0442%U044C%20%U043D%U0430%201%B0%20%U043F%U0440%U043E%U0442%U0438%U0432%20%U0447%U0430%U0441%U043E%U0432%U043E%U0439%20%U0441%U0442%U0440%U0435%U043B%U043A%U0438=Ctrl+Shift+Left
%U041F%U043E%U0432%U0435%U0440%U043D%U0443%U0442%U044C%20%U043D%U0430%2090%B0%20%U043F%U043E%20%U0447%U0430%U0441%U043E%U0432%U043E%U0439%20%U0441%U0442%U0440%U0435%U043B%U043A%U0435=Ctrl+Right
%U041F%U043E%U0432%U0435%U0440%U043D%U0443%U0442%U044C%20%U043D%U0430%2090%B0%20%U043F%U0440%U043E%U0442%U0438%U0432%20%U0447%U0430%U0441%U043E%U0432%U043E%U0439%20%U0441%U0442%U0440%U0435%U043B%U043A%U0438=Ctrl+Left
%U041F%U043E%U043A%U0430%U0437%U0430%U0442%U044C%20%U0431%U0443%U0444%U0435%U0440%20%U043E%U0431%U043C%U0435%U043D%U0430=
%U041F%U043E%U0441%U043B%U0435%U0434%U043D%U0435%U0435=End
%U041F%U0440%U0435%U0434%U044B%U0434%U0443%U0449%U0435%U0435=PgUp
%U041F%U0440%U0438%U0431%U043B%U0438%U0437%U0438%U0442%U044C=Z
%U0421%U0431%U0440%U043E%U0441%U0438%U0442%U044C%20%U043C%U0430%U0441%U0448%U0442%U0430%U0431=Ctrl+Z
%U0421%U0434%U0432%U0438%U043D%U0443%U0442%U044C%20%U0432%U0432%U0435%U0440%U0445=Up
%U0421%U0434%U0432%U0438%U043D%U0443%U0442%U044C%20%U0432%U043B%U0435%U0432%U043E=Left
%U0421%U0434%U0432%U0438%U043D%U0443%U0442%U044C%20%U0432%U043D%U0438%U0437=Down
%U0421%U0434%U0432%U0438%U043D%U0443%U0442%U044C%20%U0432%U043F%U0440%U0430%U0432%U043E=Right
%U0421%U043B%U0430%U0439%U0434-%U0448%U043E%U0443=W
%U0421%U043B%U0435%U0434%U0443%U044E%U0449%U0435%U0435=PgDown
%U0421%U043B%U0443%U0447%U0430%U0439%U043D%U043E%U0435=R
%U0421%U043E%U0445%U0440%U0430%U043D%U0438%U0442%U044C=Ctrl+S
%U0421%U043E%U0445%U0440%U0430%U043D%U0438%U0442%U044C%20%U043A%U0430%U043A=
%U0421%U043E%U0445%U0440%U0430%U043D%U0438%U0442%U044C%20%U043C%U0430%U0441%U0448%U0442%U0430%U0431=
%U0422%U0440%U0438%U0436%U0434%U044B=Ctrl+3
%U0423%U0432%U0435%U043B%U0438%U0447%U0438%U0442%U044C%20%U044D%U0441%U043A%U0438%U0437%U044B=
%U0423%U0434%U0430%U043B%U0438%U0442%U044C=Del
%U0423%U043C%U0435%U043D%U044C%U0448%U0438%U0442%U044C%20%U044D%U0441%U043A%U0438%U0437%U044B=
%U0426%U0432%U0435%U0442%U0430=C
%U0427%U0435%U0442%U044B%U0440%U0435%U0436%U0434%U044B=Ctrl+5

**Comment by oferkv** [comment] 2015-01-12 19:45
I see, well a lot has happened since 1.4.2, so I guess this is already fixed in 1.5.x.
If you wish you can validate the fix, by building 1.5.x and running locally from the build directory (no need to make install), you can see the full instructions in the Phototonic home page.
Thanks!

**Comment by Betaversiondot** [comment] 2015-01-12 20:05
Yes, this bug does not present in 1.5.1. Thank you.

**Comment by oferkv** [comment] 2015-01-12 20:26
Thanks!, closing.

**Closed by oferkv** 2015-01-12 20:26 UTC
Labels: Bug
