### ISSUE TITLE
Bug: Segmentation fault

### ISSUE THREAD

**Issue by Taur10** [oferkv/phototonic#246] opened 2018-07-06 17:28 UTC
Pretty straightforward, Phototonic suddenly closes when I try to open a folder of images on an external drive. Back when I ran Xfce, this would occasionally happen and was solved by logging out and back in, or rebooting, but I'm running Manjaro I3 now, and the problem is persistent.

Launching it from the terminal allowed me to get an error message of 'Segmentation fault (core dumped)' What is it, and how do I fix it?

**Comment by Taur10** [comment] 2018-07-07 20:54
Let's see, I'm assuming it's the latest version, 2.1-1 out of the AUR. This has happened before, off an on over the last few months.

**Comment by oferkv** [comment] 2018-07-08 08:36
Reproduction is just plugging in an external USB drive and running with the path argument?

**Comment by Taur10** [comment] 2018-07-08 17:53
External drive is always plugged in. Problem occurs for example when I use the file list and select /run/media/taurbaseds9/pictures/furry/artists then select 'include sub directories' since as you can guess, images are organized by creator.

If you need system info, that's available here: https://forum.manjaro.org/t/dump-your-inxi-fxzc0-here-and-bookmark-it/8298/149

**Comment by Taur10** [comment] 2019-01-10 21:24
Ok, having done some changes to my systems and having them run the same OS we have some more info on this. 
This problem is limited solely to my desktop system, ifn I plug the drive with my images on it into my laptop, everything works fine, but on my desktop, Phototonic fails. We've also reinstalled with the latest version on the AUR but that didn't fix the problem. Not sure if there might be a cache, preference file or some other file that might be corrupt that we can remove?

As to the systems, here are the INXI profiles:
Desktop: https://pastebin.com/baeh0tDF
Laptop: https://pastebin.com/Myc50Tnt

**Comment by oferkv** [comment] 2019-01-11 08:40
Hi Taur10;

Thanks for your report. Easiest way to resolve this that I can think of at the moment, is for you to use a debug version, and once it crashes paste the stack trace here.
So if you can, just download the source, run qmake, edit Makefile and add -g to CFLAGS and CXXFLAGS.
Then run make and make install.
Once there's a crash, locate the core dump on your system, and run this:
gdb path/to/phototonic path/to/the/core
Then type bt

Paste the stack here... :)

Thanks!

**Comment by Taur10** [comment] 2019-01-12 00:13
I'll see ifn I can do that, though my skills are rather sub-par. But I may have yet another clue. I deleted the config file, and it seems to be working at least for now.

**Comment by oferkv** [comment] 2019-01-12 11:01
Ok, thanks! I updated the instructions just in case.

**Comment by sandsmark** [comment] 2020-05-29 15:08
The best is to get a proper stacktrace like oferkv explained, but you can also just run `coredumpctl  dump phototonic` to show the stacktrace of the latest crash of phototonic (only the `Message` part is interesting).

And ideally edit the `OPTIONS=` line in /etc/makepkg.conf (before (re-) building and installing phototonic from AUR), to make sure there isn't a `!` in front of `debug` and there is a `!` in front of `strip`. So it looks something like this: `OPTIONS=(!strip docs !libtool staticlibs emptydirs zipman purge debug)`.

But I'll close this since it seems to be working for now. (I also fixed some potential crashes in master).

**Closed by sandsmark** 2020-05-29 15:09 UTC
Labels: Bug
